//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogMyWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRoles
    {
        public int Role { get; set; }
        public int ProjectID { get; set; }
        public string UserID { get; set; }
        public int ProjectRoleID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
