//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogMyWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEntries
    {
        public int EntryID { get; set; }
        public string UserID { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public bool Active { get; set; }
        public int ParentTaskID { get; set; }
        public bool Billed { get; set; }
        public Nullable<int> RateID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ProjectTasks ProjectTasks { get; set; }
        public virtual Rates Rates { get; set; }
    }
}
